import "./globals.css";
import localFont from 'next/font/local';
import { DM_Sans} from 'next/font/google';

const dmSans = DM_Sans({
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  variable: '--font-dm-sans',
});

const akiraExpanded = localFont({
  src: '../public/fonts/AkiraExpanded.woff2',
  style: 'normal',
  variable: '--font-akira-expanded'
});

const akiraOutline = localFont ({
  src: '../public/fonts/AkiraOutline.woff2',
  style: 'normal',
  variable: '--font-akira-outline'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${akiraExpanded.variable}`}>
        {children}
      </body>
    </html>
  );
}
